### ISSUE TITLE
Grabbing the image associated with each RSS article?

### ISSUE THREAD

**Issue by JeanHules** [fguillot/picoFeed#110]
This repo is great. I am using it in an idea I'm building, but cannot seem to figure out how to grab the media (image) from the xml/rss feeds.

The code I am using looks like this:

           try {
			    $reader = new Reader;
			    $resource = $reader->download($url);

			    $parser = $reader->getParser(
			        $resource->getUrl(),
			        $resource->getContent(),
			        $resource->getEncoding()
			    );
			    $feed = $parser->execute();
			}
			catch (Exception $e) {
			    // Do something...
			}

Is there an easy way to grab the <media:content> from the xml?

Thanks.

**Comment by mkresin** [comment]
Yes that's possible:

```php
$feed->items[0]->getEnclosureUrl();            // Enclosure url
$feed->items[0]->getEnclosureType();           // Enclosure mime-type (audio/mp3, image/png...)
```

**Comment by JeanHules** [comment]
That doesn't seem to work. When I echo and/or print_r $feed, the enclosure_url and enclosure_type come up empty. 

An example of an RSS feed would be: http://wildxtra.com/rss/ccs/1-Articles/

**Comment by mkresin** [comment]
My bad! ```media:content``` is a [yahoo extension](http://www.feedforall.com/mediarss.htm) to the RSS standard and not (yet) supported by picoFeed.

PicoFeed has support for the "default" [RSS 2.0 enclosure element](http://cyber.law.harvard.edu/rss/rss.html#ltenclosuregtSubelementOfLtitemgt) which does basically the same as the yahoo extension.

From my personal point of view, I don't see the need to support ```media:content``` if the standard ```enclosure``` element does more or less the same.

**Comment by JeanHules** [comment]
Ah that make sense. Do you know of a work around to work with Yahoo?

**Comment by Raydiation** [comment]
File a bug at yahoo and hope for the best ;D

**Comment by mkresin** [comment]
As far as I can see, the feed isn't provided by yahoo. Contact the feed creator/owner and please them to use the enclosure element in addition to media:content.

**Comment by fguillot** [comment]
I added a new method to the Item class, you can now fetch a non standard xml tag. In your case, something like that should work:

```php
echo $feed->items[0]->getTag('media:content', 'url');
```

More examples are provided in the documentation: https://github.com/fguillot/picoFeed/blob/master/docs/feed-parsing.markdown#get-raw-xml-tagsattributes-or-non-standard-tags-for-items

**Comment by JeanHules** [comment]
That's great. Thank you very much for adding that method. I got it working.
