### ISSUE TITLE
How to use http basic auth using picoFeed

### ISSUE THREAD

**Issue by claudyus** [fguillot/picoFeed#114]
Hello @fguillot,
it is possible to use picoFeed to fetch rss info on server that require http auth?

Thanks

**Comment by Raydiation** [comment]
@claudyus this is currently not possible and would require a patch.

**Comment by Raydiation** [comment]
The API design is not straight forward, ATM I can think of two ways:

```php
$resource = $reader->download($url, $last_modified, $etag, $user, $password);

// inside the download method
Client::getInstance()
    ->setConfig($this->config)
    ->setLastModified($last_modified)
    ->setEtag($etag)
    ->setAuth($user, $password)
    ->execute($url);

```

or

```php
$auth = new PicoFeed\Client\Auth\HttpBasicAuth($user, $password);

$resource = $reader->download($url, $last_modified, $etag, $auth);

// inside the download method
Client::getInstance()
    ->setConfig($this->config)
    ->setLastModified($last_modified)
    ->setEtag($etag)
    ->setAuth($auth)
    ->execute($url);
```

The second option needs an additional class but is more flexible (would allow other authentication implementations in the future) and keeps the download method from exploding

@mkresin thoughts?

**Comment by Raydiation** [comment]
Example for the latter example: Website requires a token as GET parameter:

```
$auth = new PicoFeed\Client\Auth\UrlTokenAuth($token);
$resource = $reader->download($url, $last_modified, $etag, $auth);
```

**Comment by mkresin** [comment]
@Raydiation way to complicated. It's nearly everything there. The client class has the required setter and I'm using http basic auth with [octom](https://github.com/mkresin/octom/blob/c01e5e11d00c85521ed5ea5bc0a7eebb86053623/octom/api.php#L74) already.

The following patch exposes username/password via ```config``` class to the ```client``` class:

```patch
diff --git a/lib/PicoFeed/Client/Client.php b/lib/PicoFeed/Client/Client.php
index 84a5cf2..a472dec 100644
--- a/lib/PicoFeed/Client/Client.php
+++ b/lib/PicoFeed/Client/Client.php
@@ -653,6 +653,8 @@ abstract class Client
             $this->setProxyPort($config->getProxyPort());
             $this->setProxyUsername($config->getProxyUsername());
             $this->setProxyPassword($config->getProxyPassword());
+            $this->setUsername($config->getUsername());
+            $this->setPassword($config->getPassword());
         }
 
         return $this;
diff --git a/lib/PicoFeed/Config/Config.php b/lib/PicoFeed/Config/Config.php
index 181da03..928dad8 100644
--- a/lib/PicoFeed/Config/Config.php
+++ b/lib/PicoFeed/Config/Config.php
@@ -33,6 +33,8 @@ namespace PicoFeed\Config;
  * @method  \PicoFeed\Config\Config setFilterImageProxyUrl($value)
  * @method  \PicoFeed\Config\Config setFilterImageProxyCallback($closure)
  * @method  \PicoFeed\Config\Config setFilterImageProxyProtocol($value)
+ * @method  \PicoFeed\Config\Config setUsername($value)
+ * @method  \PicoFeed\Config\Config setPassword($value)
  *
  * @method  integer    getClientTimeout()
  * @method  string     getClientUserAgent()
@@ -59,6 +61,8 @@ namespace PicoFeed\Config;
  * @method  string     getFilterImageProxyUrl()
  * @method  \Closure   getFilterImageProxyCallback()
  * @method  string     getFilterImageProxyProtocol()
+ * @method  string     getUsername()
+ * @method  string     getPassword()
  */
 class Config
 {
```

Which allows to setup username/password the following way:

```php
$config = new ReaderConfig;
$config->setUsername('http_user');
$config->setPassword('http_password');

$reader = new Reader($config);
$resource = $reader->download($url, $last_modified, $etag);
```

@claudyus Would you please test the patch!

@Raydiation If you do not spot something missing, I will hack up a PR later.

**Comment by Raydiation** [comment]
@mkresin thought of that too, this solution forces you to create a new reader class and config for every feed that you are fetching which is a bit weird if you are using it in a for loop, e.g.:

```php
foreach ($feedUrls as $urls) {
    $config = (new Config())->setAllParameters();
    $reader = new Reader($config);
    // etc
}
```

Also I don't think auth headers should be in the config since http auth varies from feed to feed and is therefore not global. This would be equal to setting the download URL in the config:

```php
$config->setDownloadUrl($url);
$reader = new Reader($config);
$reader->download();
```

**Comment by mkresin** [comment]
I had the miniflux code in mind, which indeed creates a new reader and config class for each feed which should be downloaded.

But your are right, the credentials are feed specific (like etag & last_modified) and should not belong to the reader config.

I like your first idea. Multiple authentication providers seams to me an overkill a the moment. They can be implemented if someone needs something else than http auth. And to be honest, I can not imagine what else then http auth could be needed to fetch feeds via http. Your token example is already possible, by appending the token to the feed url.

@Raydiation Do you write the code or should someone else take the job?

**Comment by Raydiation** [comment]
@mkresin would like to but very busy with my master thesis, no time atm :(

**Comment by claudyus** [comment]
@mkresin I test your patch and it works very well!

Great!

**Comment by mkresin** [comment]
Mhh, simply adding the username/password to the download function, results in really ugly looking function call, since most params are optional. 

For instance the following example from the docs: 

```
$resource = $reader->download('http://linuxfr.org/news.atom');
```

would be:

```
$resource = $reader->download('http://linuxfr.org/news.atom', '', '', 'username','password');
```

Any ideas?

**Comment by fguillot** [comment]
The client class already handle HTTP basic auth https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Client/Curl.php#L193-L200

The easiest solution is to add username/password parameters to the method Reader::download() like described above. It's ugly but it works.

It can also be passed to the Reader class with a couple of setters like `$reader->setUsername()` so it can be use with the method `discover()` as well.

```php
try {

    $reader = new Reader;
    $reader->setUsername('foo');
    $reader->setPassword('bar');
    $resource = $reader->discover('http://foobar');

    $parser = $reader->getParser(
        $resource->getUrl(),
        $resource->getContent(),
        $resource->getEncoding()
    );

    $feed = $parser->execute();
    echo $feed;
}
catch (PicoFeedException $e) {
}
```

**Comment by Raydiation** [comment]
In most cases you will pass the etag and last_modified parameters. In python you could do:

```python
resource = reader.download('http://linuxfr.org/news.atom', user='username', password='password');
```
which is not possible in php due to the lack of keyword parameters. You could reduce the length by 1 by simply passing in a structure/class like the auth class I've described before which would also make the method typesafe and future proof.

@fguillot since this solution wont work on more than one feed, I'd prefer that we limit it to one method invocation and not make it stateful

All in all this is maybe less of an issue than we think it is, if you dont want to use an auth object, just add the parameters and you're done, its also less code to write and won't introduce harmful state. Also using basic auth is very rare, so we should not worry that much about this kind of edge case

**Comment by Raydiation** [comment]
As in I'd vote for **$resource = $reader->download('http://linuxfr.org/news.atom', '', '', 'username','password');**

**Comment by mkresin** [comment]
@Raydiation the function call would/could be similar ugly if we're using an auth class

@fguillot adding setter to the Reader class would introduce the same weirdness mentioned in https://github.com/fguillot/picoFeed/issues/114#issuecomment-87638010

**Comment by Raydiation** [comment]
We need to provide the parameters in some way, so we need a method to set them. I'd prefer to keep them in the same method since splitting it up in multiple methods adds a bigger risk of wrong order etc. So either way we expand all the parameters or put the ones that belong together in structures, e.g.:

```php
$cache = new Cache($etag, $last_modified);
$auth = new Auth($user, $password);
$reader->download($url, $cache, $auth);
```

In JavaScript you often just pass in an object like this, which I personally consider bad though from an API usage standpoint because it silently fails if you mistype a key:

```php
$reader->download($url, array(
    'last_modified' => '', 
    'etag' => '',
    'user' => '',
    'password' => ''
));
```

**Comment by mkresin** [comment]
Even if the PR already exists, I would like to share another idea. What about introducing a http resource object?

```php
$url = new HTTPResource($url);
$url->setEtag($etag);
$url->setLastModified($etag);
$url->setUsername($username)
$url->setPassword($password)

$reader = new Reader;
$resource = $reader->download($url);
```

By checking the type of $url in download() it would be even backward compatible if desired.

**Comment by Raydiation** [comment]
@mkresin also looks fine to me and also a common solution for this problem.

**Comment by mkresin** [comment]
@fguillot let me hear what you think about my idea's. If you're considering the idea as overkill and/or you're satisfied with Bernards PR I won't start coding.

As outlined above, I'm thinking about moving all URL related setter (setUsername, setEtag etc.) from the Client Class to the new class.

**Comment by fguillot** [comment]
I merged the pull-request.

@mkresin I'm not against your proposition, if you want to implement that I will increment the version number because that change the public api. Finally, passing the `Client` class as parameter to the `download()` method is almost the same thing, instead of having a new object `HTTPResource`.

**Comment by mkresin** [comment]
It was more meant as XOR. The current solution isn't a beauty, but it isn't ugly enough to touch the code again.
