### ISSUE TITLE
Grabber/Client problems

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#121]
I've tried to work on #120 but reading the client code this piece of code confused me 

* https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Client/Client.php#L666
* https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Client/Client.php#L667

We are using the content grabber timeout and useragent for all requests, which does not seem to make sense. Is this a bug? Both seem to require the same parameters, but need a different config. I'd suggest the following solution:

* Remove the grabber config parameters
* No need to implement __clone since we are only setting pass by value values and no references
* Allow to pass an optional grabber config to the parser

```php
$clientConfig = new Config();
$clientConfig->setClientConnectTimeout(20);
$clientConfig->setClientTimeout(10); // etc

// cloning the config to override values
$grabberConfig = clone $clientConfig;
$grabberConfig->setClientTimeout(20);

$reader = new Reader($clientConfig);
$resource = $reader->download('http://linuxfr.org/news.atom');

$parser = $reader->getParser(
        $resource->getUrl(),
        $resource->getContent(),
        $resource->getEncoding(),
        $grabberConfig // optional, defaults to the reader config
);
```

@fguillot @mkresin

**Comment by mkresin** [comment]
To be honest, I've troubles to understand your question.

Am I right that you're talking about [Fetch full item contents during feed parsing](https://github.com/fguillot/picoFeed/blob/master/docs/grabber.markdown#fetch-full-item-contents-during-feed-parsing) in conjunction with the fact that ```setGrabberTimeout()``` and ```setGrabberUserAgent()``` set the values for the feed and the content (grabber) download where the function names suggest some different?

**Comment by Raydiation** [comment]
Basically the grabber and feed reader both use two entirely different clients and should be configured separately. In addition there seems to be a bug that ignores config values that are only set for the client and not for the content grabber: setting the client timeout and useragent is impossible because both use the settings for the content grabber

**Comment by mkresin** [comment]
Got it! Thanks for explanation.

As far as I can see, it is related to the mentioned "Fetch full item contents during feed parsing"  example.

In that case the same client config object is used for reader and grabber. That's why we have ```setGrabberUserAgent()```. IMHO It's intended function is to set a grabber specific client config options in that case.

If the grabber would only be used standalone, a grabber specific setter would not be necessary. It's possible to assign a client config via ```setConfig``` to the grabber. That config could be configured using ```setClientUserAgent()```.

What about doing something *untested* like:

```diff
diff --git a/lib/PicoFeed/Client/Client.php b/lib/PicoFeed/Client/Client.php
index 84a5cf2..fd7a355 100644
--- a/lib/PicoFeed/Client/Client.php
+++ b/lib/PicoFeed/Client/Client.php
@@ -645,8 +645,8 @@ abstract class Client
     public function setConfig($config)
     {
         if ($config !== null) {
-            $this->setTimeout($config->getGrabberTimeout());
-            $this->setUserAgent($config->getGrabberUserAgent());
+            $this->setTimeout($config->getClientTimeout());
+            $this->setUserAgent($config->getClientUserAgent());
             $this->setMaxRedirections($config->getMaxRedirections());
             $this->setMaxBodySize($config->getMaxBodySize());
             $this->setProxyHostname($config->getProxyHostname());
diff --git a/lib/PicoFeed/Client/Grabber.php b/lib/PicoFeed/Client/Grabber.php
index fe48904..cde63e9 100644
--- a/lib/PicoFeed/Client/Grabber.php
+++ b/lib/PicoFeed/Client/Grabber.php
@@ -316,7 +316,11 @@ class Grabber
             try {
 
                 $client = Client::getInstance();
+
                 $client->setConfig($this->config);
+                $client->setTimeout($this->config->getGrabberTimeout());
+                $client->setUserAgent($this->config->getGrabberUserAgent());
+                
                 $client->execute($this->url);
 
                 $this->url = $client->getUrl();
```

BTW: Any opinion on using the Reader constructor for Grabber as well? It's a bit confusing that both download something, but using different ways of configuration. IMHO it should be:

```php
$grabber = new Grabber($config);
$grabber->download($url, $html, $encoding);
```

Is it worse the API change?

**Comment by Raydiation** [comment]
Yep, that would fix it. 

About the grabber constructor: Yes this is actually best practice and is called dependency injection. You should pass external dependencies to the constructor to never have an object in an invalid state.

As for exploding the constructor arguments: take a look at the inversion of control and the builder pattern

**Comment by mkresin** [comment]
I'll write a patch. I'm testing the change right now.

> About the grabber constructor: Yes this is actually best practice and is called dependency injection.

My proposal is a good one or how it's done at the moment?

**Comment by Raydiation** [comment]
Yes its a good proposal

**Comment by Raydiation** [comment]
@mkresin take a look at this https://www.youtube.com/watch?v=RlfLCWKxHJ0&list=PL693EFD059797C21E
