### ISSUE TITLE
Add a way to improve feed content based on rules without downloading the page

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#128]
I am currently thinking about abandoning our website scraper in favor of the one included in picofeed, see https://github.com/owncloud/news/issues/725

Your grabber seems to always download the content based and parses the rules based on xpath. We've got another method though which circumvents the need for downloading the website's content by simply replacing things in the provided rss/atom content, which mostly consists of swapping out preview and small images for the actual content.

For instance twogag.com uses provides comics and their rss feed ships minified comic images (example: http://simplepie.org/demo/?feed=http%3A%2F%2Fwww.twogag.com%2Ffeed) and a link pointing to the original comic. In that case it is easier and faster to just replace these comics with a full size image if the image pattern is known. 

We are currently using regex for that: https://github.com/owncloud/news/blob/master/articleenhancer/regexenhancers.json

The way to go is probably to use custom filters that are run after the internal ones but only if they match a certain url. Any design ides @fguillot @mkresin ?

**Comment by fguillot** [comment]
What bout adding a new property in the rule file, by example `add_regex_content` or something similar? If this field is present that will download only this resource.

**Comment by mkresin** [comment]
> If this field is present that will download only this resource.

@fguillot @Raydiation Isn't the point to eliminate additional downloads?

What I understand, is that you apply a regex on the feed content/preview, which replaces all occurrences of http://www.twogag.com/images/preview/cat.jpg with http://www.twogag.com/images/cat.jpg. Isn't it?

So what you need are feed specific rules instead of website specific rules.

**Comment by Raydiation** [comment]
@mkresin yes, atm im matching the feed's link attribute for that

**Comment by Raydiation** [comment]
So basically we need a further distinction, e.g.:

* Rules/
 * Parser/
 * Grabber/

The current rules would go into the Grabber folder, the regex stuff would go into the Parser folder. The file name for the Parser folder would be based on the feed location domain, e.g.:

    golem.de.dynamic.feedsportal.com.php

The content would be the following:

```php
return array(
    '%.*rss\.golem\.de.*%' => array(
        'afterParsed' => function (PicoFeed\Parser\Feed $feed, PicoFeed\Parser\Item $item) {
            
        }
    )
);
```

Callback name is what came to my mind, probably not the best name :P

**Comment by mkresin** [comment]
What about:

* Rules/
 * Feed/
 * Grabber/

> The file name for the Parser folder would be based on the feed location domain

This could awfully fail for sites like http://www.01net.com/rub/actualites/10001/, where the feed url is http://rss.feedsportal.com/c/629/f/502199/index.rss.

Just an idea. What about using the Website URL provided in the feed for addressing the rule file? I have not check yet, if the url is mandatory and/or available for all formats.

**Comment by Raydiation** [comment]
Its a required element for the rss feed

    link: The URL to the HTML website corresponding to the channel.	

We could use that :)

**Comment by Raydiation** [comment]
It should be safe since since picofeed falls back to the site url when the link element is not present https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Parser/Parser.php#L208

**Comment by mkresin** [comment]
@Raydiation would it be possible to design the function in a way that it would be possible to remove advertisement from full content feeds?

According to your example rule file. What about having the following format:

```
return array(
    '/preview/full/'
);
```

and passing the regex to preg_replace? The anonymous function looks somewhat overdone for the use case you described or I've missed something obvious.

**Comment by Raydiation** [comment]
BTW: another issue I'm facing is that the Item class makes all the attributes public. The problem is that the xml which is included on the object is not synced to its attributes, e.g. $item->title = 'test' wont update the xml :/

Public attributes, baaad, getters/setters gooood.

**Comment by Raydiation** [comment]
@mkresin I'd like to reuse the dom and not settle for a regex if possible however still support it, therefore I chose a callback. Ideas?

**Comment by mkresin** [comment]
Reusing the DOM is a gooood idea :-). HTML parsing with regex is a pain.

>  Ideas?

Nope. Personally I would stick to xpath rules only (similar to the grabber rules), since my only need is to remove advertisement. Dunno if xpath is powerful enough to alter strings.

**Comment by Raydiation** [comment]
That's why I'd go for a callback :) it gives you the most flexibility, you could for instance also change the title etc

**Comment by mkresin** [comment]
Yeah, I know what you mean.

But which user is able to add custom rules if they need knowledge about php coding. I mean, even adding grabber rules is challenging for not developers. But in contrast to closures, xpath is self explaining.

Maybe we don't have the need that Johnny Average is able to add custom rules and I see ghosts.

**Comment by Raydiation** [comment]
In general I think xpath and regex are beasts of their own and actually require advanced programmers which will have no problem with the PHP syntax :)

However the main usecase for now is to do a quick search and replace. Maybe its better to get the 99% of the cases done with as few lines of code as possible but still keep the door open for later improvements that give you full control.

What about the following:

```php
<?php
return array(
    '%.*rss\.golem\.de.*%' => array(
        'content' => array(
            '%http://www.twogag.com/comics-rss/([^.]+)\\.jpg%' => 'http://www.twogag.com/comics/$1.jpg'
        )
    )
);
```

For now we'd only need to add the content field, adding filtering for the title would be possible without changing the structure and can be added once required.

The thing that follows after the content is an array for now which contains the parameters for preg_replace: $search => $replace. We can make this more flexible later on if required by checking if  the array value is a function. An array should trigger the regex mechanism, a function (if implemented) would give you full control.

**Comment by mkresin** [comment]
Now it's definitely more obvious how it's intend to be used. Has the "content" array a special purpose/future meaning/code requirement I'm not aware of? Otherwise I tend to add the replace regex directly to the match regex:

```php
<?php
return array(
    '%.*rss\.golem\.de.*%' => array(
            '%http://www.twogag.com/comics-rss/([^.]+)\\.jpg%' => 'http://www.twogag.com/comics/$1.jpg'
    )
);
```

**Comment by mkresin** [comment]
Nevermind! Re-read your comment and found the explanation for the content array.

**Comment by mkresin** [comment]
Stupid me! Re-read your comment and found the explanation for the content array. 

As of now, I don't see the need to alter a title or something else. But I don't like to bet on the future. I'm glad that's not up to me to decide to use a content/title/whatever array or not.

**Comment by Raydiation** [comment]
Good argument yeah, we can always create a PR like https://github.com/fguillot/picoFeed/pull/131 that modifies the structure should we run into new requirements. Your proposal actually looks exactly like what I currently have in the ownCloud News app. Will prepare a PR

**Comment by mkresin** [comment]
Would it make sense to add this functionality directly to https://github.com/fguillot/picoFeed/pull/131? I mean, we share the site url already and the rule file looks somehow similar.

```php
<?php
return array(
    'feed' => array(
        '%.*rss\.golem\.de.*%' => array(
            '%http://www.twogag.com/comics-rss/([^.]+)\\.jpg%' => 'http://www.twogag.com/comics/$1.jpg'
        ),
    ),
    'grabber' => array(
        '%.*%' => array(
            'test_url' => 'http://distrowatch.com/?newsid=08355',
            'body' => array(
                '//td[@class="NewsText"][1]',
            ),
            'strip' => array()
        ),
    ),
);
```

This way we could keep everything together and the user doesn't necessarily need to take care of two different files.

**Comment by Raydiation** [comment]
Yes looks good, currently fighting with the rule loader, needs to be outsourced into a separate class.

**Comment by Raydiation** [comment]
Done, please review

**Comment by fguillot** [comment]
Merged
