### ISSUE TITLE
Grabber: Make it possible to add also differ based on the sub url

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#130]
This is further work for transitioning to the picoFeed content grabber ;)

There are some feeds that feature both videos and comics (explosm.net for instance) where you also want to distinguish based on the url after the domain, or feeds where you want the default behavior except when it links to a specific video for instance.

ATM this is not possible, since the grabber only works on the domain level. 

This is the current api.:

```php
return array(
    'test_url' => 'http://www.igen.fr/ailleurs/2014/05/nvidia-va-delaisser-les-smartphones-grand-public-86031',
    'body' => array(
        '//div[contains(@class, "field-name-body")]'
    ),
    'strip' => array(),
);
```

I'd propose the following solution:

```php
return array(
    '%/videos/.*%i' => array(
        'test_url' => 'http://www.igen.fr/ailleurs/2014/05/nvidia-va-delaisser-les-smartphones-grand-public-86031',
        'body' => array(
            '//div[contains(@class, "field-name-body")]'
        ),
        'strip' => array(),
    ),
    '%.*%i' => array(
        'test_url' => 'http://www.igen.fr/ailleurs/2014/05/nvidia-va-delaisser-les-smartphones-grand-public-86031',
        'body' => array(
            '//div[contains(@class, "field-name-body")]'
        ),
        'strip' => array(),
    )
);
```

The first level is a regex that matches the sub url. It is matched in order, meaning  that the first matching entry would be taken, e.g. somedomain.com/videos/1/ would take the first array and the remaining urls would be handled by the second array.

We would ofc break compatibility in regards to the existing urls, but migrating to the new syntax should be quick and since we keep them in the same repo also not a problem. I could prepare a PR.

**Comment by Raydiation** [comment]
@fguillot @mkresin

**Comment by fguillot** [comment]
Merged
