### ISSUE TITLE
Problemas

### ISSUE THREAD

**Issue by Metalmacana** [fguillot/picoFeed#132]
Good day friend.

I'm testing this library picofeed you create. Specifically functionality "Get the list of available subscriptions for a website".

For this, I am using 4 websites that contain RSS and spread in cases where they show their website , the response obtained by the script and rss feeds containing today:

Case 1. Answer . Positive
Website: http://linuxfr.org    
Answer->  http://linuxfr.org/news.atom		
Contains ->   1 RSS

Case 2. Answer Negative.
Website: http://www.eluniversal.com 
Answer->	Array Empty   					
Contains ->	varios RSS

Case 3. Respuesta Negativa.
Website: http://www.cnn.com
Answer-> Array Empty
Contains -> varios RSS

Subcase 3. Respuesta Positiva.
Website: http://edition.cnn.com/services/rss/
Answer-> varios URLs-RSS	
Contains -> varios RSS
 
Case 4. Respuesta Positiva.
Website: http://www.el-nacional.com
Answer-> http://www.el-nacional.com/rss/	
Contains -> 1 RSS

The problem is that the script detects the RSS channel of some web pages, and in other cases don't detects.

Would you like to know how I can detect all rss a website?

Note : If we communicate in Spanish , much better because you help me better understand your comment .

**Comment by Raydiation** [comment]
* http://www.eluniversal.com does not provide a link tag that offers a subscription, see http://www.petefreitag.com/item/384.cfm
* http://www.cnn.com does not provide a link tag that offers a subscription, see http://www.petefreitag.com/item/384.cfm
* http://edition.cnn.com/services/rss/ contains multiple rss meta tags, the first one is chosen if you call the discover method

Feed discovery in general works atm when one of the following things is true for the provided URL:
* The url has an xml page with an rss or atom type
* The url has a link tag that offers a subscription, in case there are multiple tags, the first one is chosen. If you dont want that, call the find method on the reader class https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Reader/Reader.php#L116 which will return a list of all possible feeds that are provided on that page. You can then use the download method. This needs ofc more requests and is slower, you can do it like this:

```php
$url = 'http://edition.cnn.com/services/rss/';
$links = $reader->find($url, Client::getInstance()->setConfig($config)->execute($url));

// choose your link if there are more than one link
if (count($links) > 1) {
   $url = $links[$chooseHere];
}
$resource = $reader->discover($url);
```

**Comment by Metalmacana** [comment]
Thank you very much for your support. I'll try to do the things you have said and  I'll let you know.

Have a nice day.

**Comment by Raydiation** [comment]
Could you close the issue if this is fixed ;)?
