### ISSUE TITLE
Grabber: multi-page-articles

### ISSUE THREAD

**Issue by jangernert** [fguillot/picoFeed#134]
Hi,
it seems like picofeed at the moment only gets the first page of an article. It would be nice if there was a way to get all the pages and extract the content. Either some generic way (pretty hard I guess) or by custom rules for each feed.
Are there any information on how services like pocket do this?
http://getpocket.com/blog/2011/05/article-view-update-now-with-multi-page-support/

**Comment by Raydiation** [comment]
I suppose you can just add an xpath rule that matches the link to the next page. The grabber then just fetches content until that expression evaluates to false

**Comment by Raydiation** [comment]
Examples:
* http://www.golem.de/news/fuzzing-wie-man-heartbleed-haette-finden-koennen-1504-113345.html: **//li/a[contains(@class, "jtoc_next")]/@href**

Rule woudl be:
```php
<?php
return array(
    'body' => '//li/a[contains(@class, "formatted")]',
    'next_page' => '//li/a[contains(@class, "jtoc_next")]/@href'
    'strip' => array()
)
```

**Comment by fguillot** [comment]
You can also check 5filters rules: http://help.fivefilters.org/customer/portal/articles/223153-site-patterns and https://github.com/fivefilters/ftr-site-config

**Comment by joeplus** [comment]
Are the 5filter rules actually implemented? I was not able to find them in any rules files and also I could not find any reference in the scraper wiki section!

**Comment by mkresin** [comment]
> Are the 5filter rules actually implemented?

No. The 5filter rules were only mentioned as an example.

**Comment by cwmke** [comment]
Is this something that is already implemented or in discussion for the future?

**Comment by mkresin** [comment]
> Is this something that is already implemented

No.

> or discussion for the future

Not that I'm aware of. It need to be contributed by someone.

**Comment by miicha** [comment]
is there anything working in the meantime? 
@BernhardPosselt did you try your suggestion and could you get it working? because for me it isn't and I couldn't find any evaluation of the array key next_page

**Comment by BernhardPosselt** [comment]
@miicha no one commented so no one is working on it

**Comment by miicha** [comment]
OK, I will try to understand how the grabber is working and if I can implement this feature
