### ISSUE TITLE
How do we handle google feedproxy feeds in regards to the grabber?

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#136]
Just create a giant feedproxy.google.com.php file where we match the sub urls?

@fguillot @mkresin

**Comment by Raydiation** [comment]
Same goes for rss.feedsportal.com

**Comment by Raydiation** [comment]
I suppose the grabber looks at the item url and then loads the rule based on that, correct?

**Comment by mkresin** [comment]
Almost right. The grabber gets the content from item_url and uses the final redirected item_url to determine which rulefile needs to be used. Have a look at https://github.com/fguillot/picoFeed/commit/445b2adff9090c7409be055ae49e870816b70853. It explains why it has to be done that way.

**Comment by mkresin** [comment]
@Raydiation Anything unclear with my answer?
