### ISSUE TITLE
SubscriptionNotFoundException http://maximumble.thebookofbiff.com/feed/

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#137]
Any ideas why this feed throws a SubscriptionNotFoundException http://maximumble.thebookofbiff.com/feed/ ?

@fguillot

**Comment by Raydiation** [comment]
A got it, invalid feed.

**Comment by mkresin** [comment]
Even not mentioned, I feel free to answer anyway.

Using $reader->discover($url) I don't get a Exception for the feed. But the feed is malformed as indicated by the w3c feed validator. It has HTML after the closing </description> tag on line 37.
