### ISSUE TITLE
Grabber should only fetch website content if there are rules

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#140]
Apparently the content grabber uses some built in default fetch logic if no rule is present. While this may seem like a DRY feature, some feeds are ridiculously broken and there is no other way around this   other than creating a rule file which is out of question for a standard user.

If no rule is present, no website content should be fetched **at all**, the standard RSS content should be used. Only if we have a rule for a website that works, we can reliably fetch its contents.

**Comment by mkresin** [comment]
__NACK!__

At least from the miniflux point of view, the user has to enable the content grabber for each feed. If the content grabber doesn't work for a particular feed, it's up to the user to either disable the content grabber for this feed or add a rule file. Furthermore the user has the ability to get the full content of the article (s)he is currently viewing. This functionality can be used to check if the content of the website could be extracted successfully.

A lot of pages work fine with these "default" rules. Why should we remove working stuff and force the user to create a bunch of rule files with duplicate rules?

I guess you are using the content grabber in a different way. Can you describe how owncloud news uses the content grabber?

**Comment by Raydiation** [comment]
I see, makes sense if you can enable it on a per feed basis. 

As for the News app: we try to create the best experience out of the box and try to avoid settings where possible because each setting increases the test and maintenance effort (this is especially true for settings which are exposed through an graphical interface). Also the grabber comes with a cost: it at least doubles the feed update time and traffic. We have to support installations with 1000+ users.

Most feeds are "good enough" and don't require any web scraping. What I want is the best of both worlds: feeds that give you enough content should be fast to update, whereas feeds that only give you a link or a small unreadable image should be scrapped from the website.

I think our usecase and approach here is quite different, therefore I'd vote for some sort of setting.

**Comment by mkresin** [comment]
> I think our usecase and approach here is quite different, therefore I'd vote for some sort of setting.

:+1:

**Comment by fguillot** [comment]
Solved by #142
