### ISSUE TITLE
Minimize the usage of functions that cause side effects

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#141]
We should minimize functions that cause side effects, because it makes the code incredibly hard to read and maintain.

An example of this is for instance a method that sets attributes:

```php
            elseif ($everywhere) {
                Logger::setMessage(get_called_class().': Parse content with candidates');
                $this->parseContentWithCandidates();
            }
        }
        // ...
        return $this->content !== '';
```

Here we expect the parseContentWithCandidates() method to set $this->content which is totally unobvious and may lead to bugs when changing code (just ran into this very issue)

We should instead return the content directly. Most of PHPs data structures are passed by reference which basically has no performance impact:
```php
            elseif ($everywhere) {
                Logger::setMessage(get_called_class().': Parse content with candidates');
                $content = $this->parseContentWithCandidates();
            }
        }
        // ...
        return $content !== '';
```

**Comment by mkresin** [comment]
I totally agree with this. :+1:

**Comment by Raydiation** [comment]
PS: parseContentWithCandidates should also receive the things as parameters that are needed to process the stuff

**Comment by mkresin** [comment]
:+1: again. Functions without external dependencies are definitely easier to understand.

**Comment by fguillot** [comment]
It's now fixed for the methods you have mentioned.

**Comment by Raydiation** [comment]
Can you adjust the scraper? https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Scraper/Scraper.php

Tried to work on it today but gave up, too hard.

It should work like this:

```php
$html = '';
$scraper = new Scraper(new Config);
try {
    $html = $scraper->scrap($url, $needsRuleFile);

// swallowing exceptions inside the scraper is bad. It will prevent you to detect issues.
} catch (ClientException $e) {}

if ($html !== '') { 
    $item->setBody($html);
}
```

There is no need for any attributes at all on that class (except the config). All methods in there should have return values and values that are passed in.
