### ISSUE TITLE
Use constructor dependency injection instead of setter

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#143]
Very often you have to check if a config object is present and instantiate one if it isnt. This is because it is not guaranteed that it was actually passed into the constructor.

Every class that requires a config object should have a non nullable constructor parameter, e.g.:

```php
class Grabber {
    public function __construct(Config $config) 
}
```

@fguillot @mkresin watch this talk https://www.youtube.com/watch?v=RlfLCWKxHJ0&list=PL693EFD059797C21E

**Comment by fguillot** [comment]
I think the grabber class have to be rewritten, the code start to become a mess.

**Comment by fguillot** [comment]
I made some refactoring in the grabber class...

I'm also thinking about moving all grabber stuff into a subfolder "Scraper" and split the grabber class into smaller files.

**Comment by fguillot** [comment]
Moving the rule parser and the candidate parser outside of the grabber class will also improve the maintainability.

**Comment by fguillot** [comment]
It's now the case, the constructor take the Config class as argument.

I have made several refactoring like I said above.

I also renamed the Grabber class to Scraper, not sure if it was a good idea but I already done many breaking changes.

Feel free to propose any improvement/refactoring.

**Comment by Raydiation** [comment]
Naming sounds good, will take a look around the code :)
