### ISSUE TITLE
Just a hint

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#149]
Wanted to share this thing with you: http://www.w3.org/TR/upgrade-insecure-requests/#delivery

There's a new CSP directive which basically tells the browser to try https first ;)

**Comment by mkresin** [comment]
Thank you for pointing out the new CSP. I had a look at the specs and played a bit with Chrome 43 beta, which already supports upgrade-insecure-requests.

> There's a new CSP directive which basically tells the browser to try https first ;)

According to the specs and confirmed by my tests, the CSP __enforces__ HTTPS for all resources in opposite to the "try https first" you mentioned. That means, content which is only available via HTTP isn't displayed any longer.

Either I'm missed something or the CSP doesn't fit our needs.

**Comment by mkresin** [comment]
@Raydiation ^^

**Comment by Raydiation** [comment]
yep :)
