### ISSUE TITLE
Notice: iconv(): Wrong charset

### ISSUE THREAD

**Issue by acrozes** [fguillot/picoFeed#154]
The sample:

bin/picofeed feed http://photoblog.lombarda.fr/feed/rss.xml
PHP Notice:  iconv(): Wrong charset, conversion from `utf8' to `UTF-8//IGNORE' is not allowed in C:\Mes documents\moua\currss\vendor\fguillot\picofeed\lib\PicoF
eed\Encoding\Encoding.php on line 19

Notice: iconv(): Wrong charset, conversion from `utf8' to `UTF-8//IGNORE' is not allowed in C:\Mes documents\moua\currss\vendor\fguillot\picofeed\lib\PicoFeed\E
ncoding\Encoding.php on line 19
Exception thrown ===> "XML parsing error"

Maybe you should catch the error ...

**Comment by mkresin** [comment]
> PHP Notice: iconv(): Wrong charset, conversion from utf8' toUTF-8//IGNORE' is not allowed in C:\Mes documents\moua\currss\vendor\fguillot\picofeed\lib\PicoF
eed\Encoding\Encoding.php on line 19

Same as with #112. It's not possible to catch notices in php. It's made for exceptions.

A reliable encoding detection isn't possible. We had this discussion twice:

- https://github.com/fguillot/picoFeed/issues/111#issuecomment-83157802
- https://github.com/fguillot/picoFeed/pull/91#issuecomment-74413234

> Maybe you should catch the error ...

The exception is [thrown by picofeed](https://github.com/mkresin/picoFeed/blob/9fb00da21d35ab680fe271a29cd4fff29abc32cb/lib/PicoFeed/Parser/Parser.php#L140). It's up to your application to catch this exception.

**Comment by mkresin** [comment]
Forgot to mention that the encoding of the feed is horrible broken and the feed doesn't validate. Even Firefox shows only the first article because of the issues.
