### ISSUE TITLE
Doesn't fetch anything for doghousediaries

### ISSUE THREAD

**Issue by hdhoang** [fguillot/picoFeed#162]
the comic http://thedoghousediaries.com/ has it feed at http://feeds.feedburner.com/thedoghousediaries/feed?format=xml. However picofeed doesn't return anything for this, silently exit with code 255

```
% ~/picoFeed/picofeed debug http://feeds.feedburner.com/thedoghousediaries/feed\?format=xml
% echo $?
255
```

**Comment by mkresin** [comment]
Well, that's odd. It's working for me with the latest picofeed version.

* which php version do you use?
* on which operation system?
* any errors in your php error log?
* is it possible to get a copy of your php.ini (via pastebin.com)?

Would you please rerun the command with full error reporting enabled:

```
php -d error_reporting=32767 -d display_errors=On ./picofeed debug "http://feeds.feedburner.com/thedoghousediaries/feed?format=xml"
```

**Comment by hdhoang** [comment]
Thanks for the head-up, I haven't enabled iconv.so in my ini. I would appreciate it if a diagnostic message is added.

**Comment by mkresin** [comment]
> I would appreciate it if a diagnostic message is added.

Please open a new ticket for this feature request! So that it doesn't accidentally got lost.
