### ISSUE TITLE
[install] diagnostic message when iconv isn't enabled

### ISSUE THREAD

**Issue by hdhoang** [fguillot/picoFeed#163]
currently when picofeed encounters a feed that requires iconv, it silently exits with 255.

**Comment by mkresin** [comment]
The silence could be fallout from https://github.com/fguillot/picoFeed/commit/495c0d5926841d89386cc501a9d859c0bae71cbe.

**Comment by fguillot** [comment]
Required extensions are defined in the composer.json. When you install the library composer should returns an error if an extension is missing.

**Comment by Raydiation** [comment]
IMHO enough to rely on the composer requirements, it's also mentioned in the README so I think this is a non issue.

**Comment by hdhoang** [comment]
I did a git clone and then
```
% composer dumpautoload
Generating autoload files
```
and started using the picofeed binary. I'm writing rules, not creating a feed application, that's why my installation flow differs.

iconv.so is installed, but commented out (by default in my distro) in php.ini
