### ISSUE TITLE
not existent utf-8 character gets "normalized"

### ISSUE THREAD

**Issue by mkresin** [fguillot/picoFeed#168]
I'm struggling to understand an commit you made. With 10392658d4dee1a41f9398fcce35f394ca62173c you added the stripping of the character hex:e2809c08 without any testcase or futher explanation.

The problem is, there is no character in utf-8 with that hex code. What I found is the the "left double quotation mark" (U+201C), which is hex:e2809c and a [valid XML 1.0 character](http://www.w3.org/TR/xml/#NT-Char).

Can you give me a hint which issue do you fixed with this commit?

**Comment by mkresin** [comment]
Same question for the stripping of hex:c320 added in 3e1245511d61d5d13d26187e3624b48f481887c8, which isn't a valid hex code for an utf-8 character either.

IMHO it will break any utf-8 character which ends with hex:c3 and has a following space (hex:20).

**Comment by fguillot** [comment]
Those commits were quick and dirty fixes for broken feeds. If I remember correctly it was for feeds that truncate the content in the middle of utf-8 character...

But your are right, it's ugly and should be removed.

**Comment by mkresin** [comment]
Got it!

The hex:08 of hex:e2809c08 is the Backspace character which isn't valid for XML 1.0.

The hex:c320 looks like an attempt to fix ISO encoded é in UTF-8 strings, as seen in fixtures/grotte_barbu.xml. Since we decided to not take care of such encoding errors, I'll remove that replacement.
