### ISSUE TITLE
SubscriptionNotFoundException for http://www.weltreise1.de/feed/

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#174]
Here's the feed http://www.weltreise1.de/feed/

Any ideas? Running ./picofeed feed $url works which is very interesting, here's the section in my code https://github.com/owncloud/news/blob/master/fetcher/feedfetcher.php#L75

**Comment by Raydiation** [comment]
I'm running master btw, linking this issue https://github.com/owncloud/news/issues/825

**Comment by mkresin** [comment]
Works for me with miniflux + picofeed HEAD. Are you able to reproduce the issue (to make sure that it wasn't a temporary issue on the remote side)?

The only odd I can see on the quick, is that you properly pass ```null``` to the ```discover()``` function where the default values of the params are an empty string. But even with null values I do not get the exception.

Do you have [logging](https://github.com/fguillot/picoFeed/blob/master/docs/debugging.markdown) in picofeed enabled? Maybe the log reveals something useful.

**Comment by mkresin** [comment]
@Raydiation The wordpress instance blocks the owncloud news user-agent is blocked:

```
curl --head --user-agent "ownCloud News/5.3.8 (https://owncloud.org/; 1 subscriber;)" "http://www.weltreise1.de/feed/"

HTTP/1.1 403 Forbidden
```

```
curl --head --user-agent "SomeThing Else" "http://www.weltreise1.de/feed/"

HTTP/1.1 200 OK
```

**Comment by mkresin** [comment]
Muhahah, it's getting even better. It seams to me that some kind of IDS tries to prevent (SQL) injections, since the following - slightly modified - user agent does the job:

```
curl --head --user-agent "ownCloud News/5.3.8 (https://owncloud.org/; 1 subscriber)" "http://www.weltreise1.de/feed/"

HTTP/1.1 200 OK
```

**Comment by Raydiation** [comment]
XD OK thanks for debugging

**Comment by cosenal** [comment]
oh boy! this was hard to catch, thanks @mkresin
