### ISSUE TITLE
explosm.net enhancer writes additional src into body

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#181]
![bug](https://cloud.githubusercontent.com/assets/195053/9244811/1498bac6-419f-11e5-8c80-98f51f94f4b1.png)

This is on master with content grabber enabled

**Comment by mkresin** [comment]
IMHO it's intentionally: c7085c4a533990f39eec139e6bfa70a885fbcd78.

If you don't agree with the change, feel free to add the author of the mention commit to this issue and discuss about the reason for this change.
