### ISSUE TITLE
Using the HTML filter is unnecessarily hard

### ISSUE THREAD

**Issue by BernhardPosselt** [fguillot/picoFeed#194]
I'm trying to move off HTMLPurifier since the documentation sucks and HTML standard support is always lacking behind.

The only thing that still lets me keep it is that I need to filter imported articles' HTML. How do I do that?

```php
$html = new PicoFeed\Filter\Html($html, $url);
$html->setConfig($myConfig);
$html = $html->execute();
```

What about simply doing:

```php
$html = new PicoFeed\Filter\Html($config);
$html = $html->filter($html, $url);
```

That would make it easy to reuse the same instance, remove constructor work and also clarify the API

**Comment by fguillot** [comment]
I agree, you can send a pull-request if you have time to do the modification.

**Comment by BernhardPosselt** [comment]
On it :)
