### ISSUE TITLE
iphoneblog.de feed problem

### ISSUE THREAD

**Issue by aschilling** [fguillot/picoFeed#199]
Hi,

the following feed http://www.iphoneblog.de/feed/ provides some missmatch between blog articles and comments. For example, yesterday, a comment from 2008 was identified by PicoFeed. The author of the blog seems to be aware of the problem (http://www.iphoneblog.de/2015/08/31/iphoneblog-de-version-4-2/) but does not know how to fix it for self-hosted feed readers. Do you have an idea how to fix that issue in PicoFeed or do you have a recommendation for the author?

Thanks

**Comment by BernhardPosselt** [comment]
Nope, what do you expect ;)?

**Comment by mkresin** [comment]
@aschilling  Would you please close the ticket! There is nothing we can do for you.
