### ISSUE TITLE
Grabber Fails to Fetch Content From onmilwaukee.com

### ISSUE THREAD

**Issue by cwmke** [fguillot/picoFeed#222]
onmilwaukee.com does not seem to be able to grab the content at all and I'm at a loss as to why that would be.  Any help will be greatly appreciated.  The feed pulls new articles in with no trouble, http://onmilwaukee.com/rss/rss.xml.

I have attempted many different xpaths with no success.  The rules file is labeled onmilwaukee.com.php and contains the following,

~~~
<?php

return array(
    'grabber' => array(
        '%.*%' => array(
            'test_url' => 'http://onmilwaukee.com/movies/articles/downerspelunking.html',
            'body' => array(
                '//article[@class="show"]',
            ),
            'strip' => array(
                'h1',
                'div[contains(@class,"_ad")]',
                'div[contains(@class,"-ad")]',
                'div[@id="pub_wrapper"]',
                'div[@class="share_tools"]',
                'div[@class="clearfix"]',
                'div[contains(@class,"image_control")]',
                'section[@class="ribboned"]',
            ),
        ),
    ),
);
~~~

**Comment by mkresin** [comment]
It isn't your fault, the site is malformed.

The website reports that the used encoding is "UTF-8" but instead it's "windows-1252". Therefore picofeed can not process the website content properly.

I'm sorry, but there is nothing we can do for you.

Please contact the site webmaster, report the issue and hope that they will fix their site. Fell free to forward the following link to the webmaster: https://validator.w3.org/nu/?doc=http%3A%2F%2Fonmilwaukee.com%2Fmovies%2Farticles%2Fdownerspelunking.html.

Dev-Info:

- [stripHeadTags](https://github.com/fguillot/picoFeed/blob/59714342fa302a07f50e44e4a8b61fde71d814a8/lib/PicoFeed/Filter/Filter.php#L90) returns an empty string
- if I remove the u (PCRE_UTF8) modifier everything works for this site
- if I fixup the charset meta tag for a local copy of the site, it does work as well

**Comment by cwmke** [comment]
Thanks for all of the information!  I'll get in touch with the webmaster and keep my fingers crossed.
