### ISSUE TITLE
Favicon extract pulls wrong icons

### ISSUE THREAD

**Issue by joshas** [fguillot/picoFeed#231]
There's an issue with Favicon extract() function on www.smashingmagazine.com website (and possibly others). rel="mask-icon" is picked up as favicon and returned in icons array. Query used in extract() function needs to be more specific, not to pick up invalid favicons.

**Comment by BernhardPosselt** [comment]
https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Reader/Favicon.php#L198

Solution is probably to fix the xpath from 

```xpath
//link[contains(@rel, 'icon') and not(contains(@rel, 'apple'))]
```

to 

```xpath
//link[@rel="icon" or @rel="shortcut icon" or @rel="shortcut icon"]
```

Can you check if the change works and create a pull request?
