### ISSUE TITLE
Support for SVG image types

### ISSUE THREAD

**Issue by joshas** [fguillot/picoFeed#232]
Currently Favicon class is limited to 'image/png', 'image/gif', 'image/x-icon', 'image/jpeg', 'image/jpg' image types. SVG mime type 'image/svg+xml' should be added, as more websites started using SVG favicons.

**Comment by BernhardPosselt** [comment]
Feel free to create a Pull Request, it's only one line to add ;) https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Reader/Favicon.php#L32
