### ISSUE TITLE
Feeds aggregation

### ISSUE THREAD

**Issue by louisbeziau** [fguillot/picoFeed#244]
Hello,
Is there a way to aggregate feeds with picoFeed ?

**Comment by BernhardPosselt** [comment]
What do you mean?

**Comment by louisbeziau** [comment]
I want to agregate multiple feeds and display one feed containing all their article on my website

**Comment by BernhardPosselt** [comment]
Yes, thats possible however there is no high level API for this (and you will need to rewrite the guid for each item)

Just loop over a list of URLs, fetch the feed and its items and concat them into a new list with rewritten guids.

**Comment by louisbeziau** [comment]
Thanks
