### ISSUE TITLE
If no <pubDate>, $item->getDate() returns a new DateTime("now") instead of NULL

### ISSUE THREAD

**Issue by soywod** [fguillot/picoFeed#246]
Hi,
I'm not sure if it's a bug or not, I need your opinion. If a RSS feed (2.0) has no `<pubDate>` tag in its items, then `$item->getDate()` returns a `new DateTime("now")`. I know it's the feed fault's, but maybe `$item->getDate()` should returns `NULL`. I have to create a RSS reader, and every X minutes, for each items, I check if `$item->getDate() > $last_update`. With a RSS feed with no `<pubDate>`, it adds all existing posts because $now is always > $last_update. Is there another way to know if `<pubDate>` is here ?

I hope I've been understandable, 
Regards

**Comment by BernhardPosselt** [comment]
First of all we need to distinguish between two things here:
* Date when an item was created
* Date when an item was updated

IMHO it's fine to return the current date if no created date was given (since it was recorded at that point in time), but it's definitely wrong for updated items.

I think this should be solved by providing a way to check if an item was updated. This would also preserve backwards compatability:

```php
// $lastDateTime is persisted in the database
if ($item->wasUpdated($lastDateTime) {
    // update the database tables
}
```

The wasUpdated method could look something like this:

```php
public function wasUpdated(DateTime $lastDateTime) {
    return $lastDateTime !== null && $this->getDate() !== null && $lastDateTime > $this->getDate();
}
```

**Comment by soywod** [comment]
So you are agree with me if there is no created neither updated date, `$item->getDate()` should returns `NULL` instead of now ? Indeed a `wasUpdated` could be a nice feature to implement.

Maybe I should not focus on date, but on IDs (so I'll cover more RSS feeds, including bad feeds w/o dates). I'll take only posts that IDs are unknown (or > $oldID).

**Comment by BernhardPosselt** [comment]
> So you are agree with me, if there is no created neither updated date, $item->getDate() should returns NULL instead of now ? Indeed a wasUpdated could be a nice feature to implement.

All I'm saying is that you are pondering a different usecase, so returning NULL might not be the solution you want

> Maybe I should not focus on date, but on IDs (so I'll cover more RSS feeds, including bad feeds w/o dates). I'll take only posts that IDs are unknown (or > $oldID).

Yep, there are some feeds (youtube) that "misbehave" as in: they will set their feed as updated if a comment was added to the video. These comments aren't even in the feed :)
A more robust way woudl be to hash over title, url, body and enclosures and compare that hash with the one in the database. That way you can figure out if relevant information changed and update the item accordingly. This will catch all updates and also work for feeds that did not correctly implement the pub date

**Comment by soywod** [comment]
> All I'm saying is that you are pondering a different usecase, so returning NULL might not be the solution you want

Maybe :/

> All I'm saying is that you are pondering a different usecase, so returning NULL might not be the solution you want

Yeah you're right, I think I'll go in this direction. Thx for your help :)
