### ISSUE TITLE
Heise RSS feed can not be parsed

### ISSUE THREAD

**Issue by wamserma** [fguillot/picoFeed#265]
The Heise News-Feeds is erroneously declared as empty: http://www.heise.de/newsticker/heise.rdf
The feed validates with the W3C: https://www.w3.org/RDF/Validator/rdfval?URI=http%3A%2F%2Fwww.heise.de%2Fnewsticker%2Fheise.rdf&PARSE=Parse+URI%3A+&TRIPLES_AND_GRAPH=PRINT_TRIPLES&FORMAT=PNG_EMBED
The alternative ATOM-Feed is working.
Bug discovered via Miniflux (latest release), see https://github.com/miniflux/miniflux/issues/513

This is different from https://github.com/fguillot/picoFeed/issues/224

**Comment by fguillot** [comment]
The issue should be fixed in master.

Thanks
