### ISSUE TITLE
Read articles come up as unread with unchanged feed (e.g. ccc.de)

### ISSUE THREAD

**Issue by wamserma** [fguillot/picoFeed#266]
Articles from this feed https://www.ccc.de/de/rss/updates.xml show up as unread after the refresh (mostly through cronjob, not with manual refresh). Same with the ATOM-Feed.

**Comment by BernhardPosselt** [comment]
What does "come up as unread" mean?

**Comment by BernhardPosselt** [comment]
AFAIK picoFeed does not have an unread functionality

**Comment by wamserma** [comment]
The articles show up again on the unread tab of Miniflux as if they never had been marked as read.
Right now even after I deactivated the feed in Miniflux, so it might be a DB issue on the Miniflux side, see also https://github.com/miniflux/miniflux/issues/514

**Comment by BernhardPosselt** [comment]
I think this issue can be closed :)
