### ISSUE TITLE
Edit multiple subscriptions | tags | sanity

### ISSUE THREAD

**Issue by mjbe** [fguillot/picoFeed#280]
A means to edit tags for multiple subscriptions would be very helpful.

The tag / group feature implies an admission that some people have so many subscriptions that they can be organised only if they can be grouped.

By the same reasoning it is unfeasible to organise a large number of feeds into groups without the means to treat multiples of them simultaneously. Likewise, other subscription settings.

miniflux, however, requires a user to edit each subscription's tags individually. This effectively makes the task impossible.

As it happens, I had already invested a lot of time into organising my feeds into groups. miniflux did not retain their groups when it imported them.

Having given a means to select *feed-items* by tag, miniflux has created a need also to select *feeds* by tag. That is, if a user has so many feeds that tags are necessary, then it is likely they would need to filter by feed as well, or even simply by feed alone.

It may be that, having many more than 600 feeds and requiring many more still, my 'life is cluttered' ;-), but it needn't be cluttered; if only it was effortless to categorise them.

The reason I have many feeds is that my professional domain is broad and deep. As the world becomes more connected and sources of information grow, and points of relevance multiply too, it just gets broader and broader, and deeper and deeper. If only it were narrow or focused, then it would be trivial to read my feeds efficiently.

I hope you agree. miniflux looks rather nice. I do expect, having introduced groups, that you must share my views on this anyway.

I wonder meanwhile if it is possible to access the feed metadata in a spreadsheet, and edit it that way?

**Comment by BernhardPosselt** [comment]
You are posting this in the wrong repo ;)

**Comment by mjbe** [comment]
Oh what do I know? I am but a mere mortal. And the miniflux documentation points to fguillot's github page for feedback, while the only mention of RSS on guillot's github page points here!-)
