### ISSUE TITLE
Add Setter for adding a CSS/Style to the RSS

### ISSUE THREAD

**Issue by typoworx-de** [fguillot/picoFeed#282]
This would be a nice-to-have feature - just because RSS can and in some cases it also might make sense.

**Comment by BernhardPosselt** [comment]
Styles are stripped by (probably) all feed aggregators because they pose XSS risks. If you are talking about styles for the your RSS publishing page, that's your decision ;)

**Comment by alex94040** [comment]
It would be great to have a setting that determines whether the styles are included or not. I bet that setting is there, I just can't find the documentation for it..

**Comment by elmanell** [comment]
The style attribute is a potential xss risk that's why it's filtered. Because of that a setter doesn't make sense IMHO
