### ISSUE TITLE
How to check that content was grabbed from site or got directly from RSS feed?

### ISSUE THREAD

**Issue by rakshazi** [fguillot/picoFeed#298]
Hello!
Here is example:
1. I have picofeed and rules for example.site
2. When picofeed runs, it grabs content from site pages, because I have right rules for this site.
3. When example.site changes his markup, picofeed returns content from RSS/Atom feed, not from site pages.

How to check if content was grabbed from site pages (using grabber rules) or from RSS/Atom feed `<description>` tag (when grabber rules are wrong or missing)?

Best regards, Nikita.

**Comment by rakshazi** [comment]
@BernhardPosselt @fguillot hello!
Can you help me with this problem?

**Comment by fguillot** [comment]
You should have more information in the debug logs, at least you will see what's happening during the parsing.

**Comment by rakshazi** [comment]
but I want automaticaly check it, logs is not good idea for this

**Comment by rakshazi** [comment]
@fguillot I want do something like this:
```php
$content = $parser->execute();
if($parser->isGrabbed()) {
    echo 'Content was downloaded using grabber rules';
} else {
    echo 'Content was downloaded without grabber rules (rules for this url was not found or broken)';
}
```

**Comment by rakshazi** [comment]
May be this will work:
```php
$parser->enableContentGrabber(true, function($feed, $item, $scraper){
    $item->isGrabbed = $scraper->hasRelevantContent();
})
$content = $parser->execute();
//...
if($picoFeedParserItem->isGrabbed) {
    echo 'Content was downloaded using grabber rules';
} else {
    echo 'Content was downloaded without grabber rules (rules for this url was not found or broken)';
}
```

Please, tell me, is it the right way?

**Comment by rakshazi** [comment]
@fguillot ?

**Comment by BernhardPosselt** [comment]
@rakshazi did you find a solution yet?

**Comment by rakshazi** [comment]
@BernhardPosselt I think that https://github.com/fguillot/picoFeed/issues/298#issuecomment-263976338 must work, but not tried it yet
