### ISSUE TITLE
Worldpress tags : description, category, etc.

### ISSUE THREAD

**Issue by thierryler** [fguillot/picoFeed#299]
Hello,

Reading a RSS from worldpress (this one https://profil4.wordpress.com/feed), I have tags category, description, and others in item. Actually description contains a summary of the item :

```
<channel>
  <item>
    <category><![CDATA[car]]></category>
    <category><![CDATA[motor]]></category>
    <description>Some short text...</description>
    ...
```

How can I get those values ?

**Comment by BernhardPosselt** [comment]
Check the docs: https://github.com/fguillot/picoFeed/blob/master/docs/feed-parsing.markdown ;)
