### ISSUE TITLE
web scraper rules should allow for content-encoding conversion

### ISSUE THREAD

**Issue by stopped** [fguillot/picoFeed#43]
web scraper rules should allow for content-encoding conversion.

If a feed source publishes content in, say, ISO-8859-2 it should be possible to conert it to UTF-8 before being passed on the calling application (eg. miniflux).

**Comment by mkresin** [comment]
@stopped Any content that is fetched from a website by the grabber is automatically converted to UTF-8 for a long time now. I've the impression this ticket is kind of outdated.

Would you please close the ticket!
