### ISSUE TITLE
Fatal error when ->discover($url) where $url has no RSS feed

### ISSUE THREAD

**Issue by kennyfranks** [fguillot/picoFeed#86]
When a url provides no found rss feed url (for example $reader->discover("dailynews.com") the program terminates with Fatal Error('url cannot be found) which is generated in the Curl Class.
How to handle a url which has no/ or finds no associated rss feed??

CODE__________________________________________________________________________
try
							{
								$reader = new Reader;
								$reader->discover($newFeed);
								$parser = $reader->getParser($resource->getUrl(), $resource->getContent(), $resource->getEncoding());
								$feed = $parser->execute();
								//$picoLink = $feed->getUrl();
							}
							catch( Exception $e)
							{
								echo $e->getMessage();
								$feedback = "NO RSS Feed found for " . $newFeed . ".<br>Find and input the RSS feed link directly.";
								$picoIsGood = false;
								return false;
							}

OUTPUT____________________________________________________________________

Unable to find a subscription Fatal error: Uncaught exception 'PicoFeed\Client\InvalidUrlException' with message 'Unable to resolve hostname' in /hsphere/local/home/knowem1/publish.knowem.com/php/vendor/fguillot/picofeed/lib/PicoFeed/Client/Curl.php:302 Stack trace: #0 /hsphere/local/home/knowem1/publish.knowem.com/php/vendor/fguillot/picofeed/lib/PicoFeed/Client/Curl.php(200): PicoFeed\Client\Curl->handleError(6) #1 /hsphere/local/home/knowem1/publish.knowem.com/php/vendor/fguillot/picofeed/lib/PicoFeed/Client/Curl.php(215): PicoFeed\Client\Curl->executeContext() #2 /hsphere/local/home/knowem1/publish.knowem.com/php/vendor/fguillot/picofeed/lib/PicoFeed/Client/Client.php(173): PicoFeed\Client\Curl->doRequest() #3 /hsphere/local/home/knowem1/publish.knowem.com/php/vendor/fguillot/picofeed/lib/PicoFeed/Reader/Reader.php(73): PicoFeed\Client\Client->execute('http://') #4 /hsphere/local/home/knowem1/publish.knowem.com/php/vendor/fguillot/picofeed/lib/PicoFeed/Reader/Reader.php(87): PicoFeed\Reader\Reader->download(NULL, '', '') #5 /hsphere/local/home/kno in /hsphere/local/home/knowem1/publish.knowem.com/php/vendor/fguillot/picofeed/lib/PicoFeed/Client/Curl.php on line 302

**Comment by Raydiation** [comment]
You need to catch the error ;)

**Comment by Raydiation** [comment]
Check https://github.com/owncloud/news/blob/master/fetcher/feedfetcher.php#L76

**Comment by kennyfranks** [comment]
Got it figured out. I was catching the exception in code but was still seeing the exception thrown in the logs. Turned out my IDE was not transferring the updated file to the server. 

All good. Thanks!
