### ISSUE TITLE
published date and time should return a php DateTime instance instead of a timestamp

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#96]
The date attribute on the feed should be an instance of http://php.net/manual/en/class.datetime.php so that there can't be overflow parsing problems with dates far in the future or before 1970. Getting the Unix time from a datetime object is as simple as calling the getTimestamp method on it

**Comment by fguillot** [comment]
It's is done in master, feed/item date returns a DateTime object now.

Versions <= 0.1.2 returns the timestamp (breaking change).

**Comment by Raydiation** [comment]
\o/ thanks
