### ISSUE TITLE
<script> tags in atom feeds are converted to div tags instead of being stripped out

### ISSUE THREAD

**Issue by Raydiation** [fguillot/picoFeed#97]
Cross linking https://github.com/owncloud/news/issues/723

**Comment by fguillot** [comment]
Do you know the url feed?

**Comment by mkresin** [comment]
According to https://github.com/owncloud/news/issues/723#issuecomment-73726283 it is the paid ("premium") version of http://rss.golem.de/rss.php?feed=ATOM1.0.

I can reproduce the issue with the demo feed https://gist.githubusercontent.com/cosenal/b803844b747e180cec92/raw/786320a8f5f2a4e72ac42eb1c5bb2c0ffd5f8b38/feed.xml provided in https://github.com/owncloud/news/issues/723#issuecomment-73918941.

**Comment by Raydiation** [comment]
I think the issue is that picoFeed does not properly parse atom feeds. I dont see a distinction between text/html content in the parser, see http://www.xml.com/pub/a/2005/12/07/handling-atom-text-and-content-constructs.html 

For instance 
```xml
<title type="html">One &lt;strong&gt;bold&lt;/strong&gt; foot forward</title>
```
should decode the html entities inside the tag (if its not wrapped in CDATA)

The type can be on any text element (i guess) and be one of the following strings:
* text
* html
* xhtml
* image/png (also with src)
* text/html
* image/svg+xml
* etc...

We should however limit it to text, html and xhtml. Beware of all the other stuff, especially svg. Carelessly embedding an svg within HTML can lead to XSS since you can include script tags and CSS!

**Comment by Raydiation** [comment]
Also http://atomenabled.org/developers/syndication/

**Comment by Raydiation** [comment]
I think the problem is this line https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Parser/Atom.php#L323

I suppose the count is 0 if the content is escaped html with type="html"

**Comment by mkresin** [comment]
As far as I can see, it is something in between. The type attribute isn't evaluated, but whitelisted html tags are preserved. All unknown (not whitelisted) html tags are removed, but their textual content is preserved. 

IMHO it's a good compromise of being prone to XSS and keeping as much of the content as possible.

It would be feasible to define a blacklist of tags, which get removed including their content.

**Comment by Raydiation** [comment]
Ok, so I've debugged this a bit further and the startTag and endTag methods here https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Filter/Html.php#L157 seem to be the problematic piece of code. 

The best thing should be like you mentioned to add something like a preFilter() (much like postFilter) which just removes blacklisted tags from the Tag class
